# 현재 작업 경로 알아보기

In [38]:
%pwd

'C:\\Users\\rkdus3696'

#파일 작성

In [40]:
%%writefile hi.txt
hello
# hi 라는 txt 파일에 hello가 적혀있을 것
#형식 매우 중요하니까 중간에 한글을 넣거나 다른 문자를 넣는 행위는 자제해야한다
#정해진 틀이 엄격한 편

Writing hi.txt


In [41]:
%%writefile hi.txt
hello cat

Overwriting hi.txt


In [42]:
#overwriting 한 것으로 파일을 다시 열면 cat이 추가되어 있을 것이다
#이것도 조심해야 한다 #표시된 것도 같이 메모되기 때문이다

In [43]:
!dir hi.txt

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 2A41-5FED

 C:\Users\rkdus3696 디렉터리

2024-09-22  오후 11:14                11 hi.txt
               1개 파일                  11 바이트
               0개 디렉터리   8,068,567,040 바이트 남음


In [45]:
#dir은 현재 위치에 있는 파일 리스트를 알려준다
#!는 명령프롬포트에서 쓰는 것과 같은 역할을 한다

#프로그램 실행

In [46]:
%%writefile myRead.py
import os

print(os.getcwd())
f=open('myRead.py','r')
lineNum=0
for line in f.readlines():
    lineNum+=1
    print(lineNum,"-",line)
f.close()

Writing myRead.py


	현재 작업디렉토리 출력
open(파일명,모드)	파일을 읽기 용도로 열기
	파일에서 읽기
lineNum = 0	줄 수를 출력하기 위해 초기화
	줄 수, 한 줄씩 출력하기
	파일 닫기

In [48]:
!dir myRead.py

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 2A41-5FED

 C:\Users\rkdus3696 디렉터리

2024-09-22  오후 11:17               153 myRead.py
               1개 파일                 153 바이트
               0개 디렉터리   8,065,716,224 바이트 남음


읽어오기

In [49]:
%run myRead.py

C:\Users\rkdus3696
1 - import os

2 - 

3 - print(os.getcwd())

4 - f=open('myRead.py','r')

5 - lineNum=0

6 - for line in f.readlines():

7 -     lineNum+=1

8 -     print(lineNum,"-",line)

9 - f.close()



In [50]:
#같은 방법으로 명령프롬포트에서 실행하기

In [51]:
!python myRead.py

C:\Users\rkdus3696
1 - import os

2 - 

3 - print(os.getcwd())

4 - f=open('myRead.py','r')

5 - lineNum=0

6 - for line in f.readlines():

7 -     lineNum+=1

8 -     print(lineNum,"-",line)

9 - f.close()



#numpy 배열 다루기

In [53]:
import numpy as np

a = np.array([0, 1, 2])
print(a) 

# numpy는 배열 프로그래밍을 지원하는 것, 그리고 이때의 데이터 형태가 array(배열) 형태인 것다다

[0 1 2]


배열을 생성할 수 있는 다양한 함수들:
- np.arange(start, stop, step): 주어진 범위 내에서 일정한 간격으로 값을 생성
- np.zeros(shape): 주어진 형태(shape)와 데이터 타입을 가지는 0으로 채워진 배열
- np.ones(shape): 주어진 형태(shape)와 데이터 타입을 가지는 1로 채워진 배열
- np.empty(): np.ones()와 비슷하지만, 초기화되지 않음(즉, 임의의 값들로 채워짐).
- np.linespace(start, stop, n): 등간격 배열
- np.logspace(start, stop, n): 로그 스케일의 등간격 배열
- np.eye(N): 주어진 크기의 단위 행렬(identity matrix)을 생성

In [54]:
c = np.arange(10)
print(c)  # [0 1 2 3 4 5 6 7 8 9]

d = np.zeros((2, 3))
print(d)
# [[0. 0. 0.]
#  [0. 0. 0.]]

e = np.ones((2, 3))
print(e)
# [[1. 1. 1.]
#  [1. 1. 1.]]

print(f"empty: {np.empty(2)} empty3x3float: {np.empty((3, 3), dtype=float)}")

print(f"linspace: {np.linspace(0, 10, num=5)}")
print(f"logspace: {np.logspace(0, 5, 5)}") # 10의 0 ~ 5 승 5개

f = np.eye(4)
print(f)

[0 1 2 3 4 5 6 7 8 9]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
empty: [6.01346953e-154 8.94213159e+130] empty3x3float: [[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 8.59674224e-321]
 [8.34445137e-308 2.14321575e-312 2.29178686e-312]]
linspace: [ 0.   2.5  5.   7.5 10. ]
logspace: [1.00000000e+00 1.77827941e+01 3.16227766e+02 5.62341325e+03
 1.00000000e+05]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [55]:
#ndim 차원
#size 길이
#shape 행, 열의 모양

In [56]:
# 1차원 배열
a = np.array([1, 2, 3])
print(f"shape:{a.shape} size:{a.size}")  # (3,)

# 2차원 배열
b = np.array([[1, 2, 3], [4, 5, 6]])
print(f"shape: {b.shape} ndim: {b.ndim}")  # shape: (2, 3) ndim: 2

# 다차원 배열
c = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(c.shape)  # (2, 2, 3)

shape:(3,) size:3
shape: (2, 3) ndim: 2
(2, 2, 3)


In [57]:
# 정수형 배열
a2=np.array([3,4,5], float)
print(a2.dtype) #float64

int_array = np.array([1, 2, 3], dtype=np.int32)
print(int_array.dtype)  # int32

# 실수형 배열
float_array = np.array([1.0, 2.0, 3.0], dtype=np.float64)
print(float_array.dtype)  # float64

# 복소수형 배열
complex_array = np.array([1+2j, 3+4j], dtype=np.complex128)
print(complex_array.dtype)  # complex128

float64
int32
float64
complex128


In [58]:
import numpy as np

dtype_example = np.dtype({'names': ['A', 'B', 'C'], 'formats': ['<f4', '|f4', '|f4']})

data = np.array([(1.0, 2.0, 3.0), (4.0, 5.0, 6.0)], dtype=dtype_example)

print(data['A'])  # [1. 4.]
print(data['B'])  # [2. 5.]
print(data['C'])  # [3. 6.]

[1. 4.]
[2. 5.]
[3. 6.]


In [59]:
import numpy as np

# 3x3 배열 생성
f = np.ones((3, 3))
print(f)
# [[1. 1. 1.]
#  [1. 1. 1.]
#  [1. 1. 1.]]

# 첫 번째 행, 두 번째 열의 요소 접근
print(f[0][1])  # 1.0

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
1.0


In [60]:
print(f[0])  # [1. 1. 1.] 첫 번째 행 전체를 가져오기

print(f[0][:2])  # [1. 1.] 첫 번째 행의 첫 두 요소를 가져오기


print(f[:2]) # 첫 두 행을 가져오기
# [[1. 1. 1.]
#  [1. 1. 1.]]

[1. 1. 1.]
[1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [63]:
# 나머지 :: % 계산
# numpy 배열은 같은 위치의 요소들끼리 항목별 계산 elementwise operations 가능 등등등...

In [64]:
v = np.array([1, 2, 3, 4, 5], float)

print(v.sum())      # 합계: 15.0
print(v.prod())     # 곱: 120.0

print(np.sum(v))    # 합계: 15.0
print(np.prod(v))   # 곱: 120.0

print(v.argmin())   # 최소값의 인덱스: 0
print(v.argmax())   # 최대값의 인덱스: 4

w = np.array([[1, 2, 3], [4, 5, 6]])
print("sum0: ", w.sum(axis=0)) # 행을 따라 합계 (열별 합계) [5 7 9]
print("sum1: ", w.sum(axis=1)) # 열을 따라 합계 (행별 합계) [ 6 15]

print("평균0: ", w.mean(axis=0))  # [2.5 3.5 4.5] 열에 대한 평균

print("평균1: ", w.mean(axis=1))  # [2. 5.] 행에 대한 평균
 
print("min0: ", w.min(axis=0))   # [1 2 3] 열에 대한 최솟값

print("min1: ", w.max(axis=1))   # [3 6] 행에 대한 최댓값

15.0
120.0
15.0
120.0
0
4
sum0:  [5 7 9]
sum1:  [ 6 15]
평균0:  [2.5 3.5 4.5]
평균1:  [2. 5.]
min0:  [1 2 3]
min1:  [3 6]


#무작위수 생성하기

In [65]:
print(np.random.rand(10)) # 0에서 1 사이의 균등 분포를 따르는 무작위 수

print(np.random.randint(0, 9)) #5

print(np.random.normal(170,10)) # 평균 170, 표준편차 10을 갖는 정규 분포에서 무작위 수 생성

[0.42514271 0.30615149 0.17619986 0.43249563 0.42561686 0.3837179
 0.25932203 0.51525816 0.52510937 0.68390639]
3
160.1654329699363


#배열과 반복문

In [66]:
x=range(1,101)
total=0

for i in x:
    total+=i


print(f"sumFor: {total}") #5050
print(f"sumnp: {np.sum(x)}") #5050
print(f"sumnp: {np.array(x).sum()}") #5050

sumFor: 5050
sumnp: 5050
sumnp: 5050


In [67]:
#np.dot() => 파이썬의 내적 계산

In [69]:
import numpy as np
print(np.prod([3,4,5,6,7])) #2520 *내부 elements의 곱
print(np.dot([3,4,5,6,7],[3,4,5,6,7])) #135 = 3x3 + 4x4 + 5x5 + 6x6 + 7x7

2520
135


In [73]:
x=range(1,101)
total=0
for i in x:
    total+=i**2

print(f"sumSqFor:{total}") # 338350
print(f"sumSqdot:{np.dot(x,x)}") #338350

_x=np.linspace(1, 100, num=100)
print(f"sumSqnp:{np.sum(_x*_x)}") #338350

sumSqFor:338350
sumSqdot:338350
sumSqnp:338350.0


In [74]:
import numpy as np

y = np.array([[6, 8, 4, 5, 3, 4], 
              [8, 12, 9, 13, 6, 8], 
              [13, 9, 11, 8, 7, 12]])

In [75]:
np.set_printoptions(precision=1) # 소수점 이하 자릿수를 1자리로 설정
print(y.mean(axis=0))  # 각 열의 평균(axis=0)
np.set_printoptions(precision=0) # 소수점 이하 자릿수를 0으로 설정
print(y.mean(axis=1)) # 각 행의 평균(axis=1)
np.set_printoptions(suppress=True) # 지수 표기법을 사용하지 않는다.
print(y.mean(axis=0)) # 각 행의 평균(axis=1)
np.set_printoptions(precision=2)

[9.  9.7 8.  8.7 5.3 8. ]
[ 5.  9. 10.]
[ 9. 10.  8.  9.  5.  8.]


## matrix 는 np.arry에서 나타낼 수 있는 data중 2차원 data를 표현하는 경우 사용 가능
# == 2d array

In [82]:
m1 = np.asmatrix([[1, 2], [3, 4]])
m2 = np.asmatrix([[5, 6], [7, 8]])

print(m1)
print(m2)
print(m1 * m2) # np.matrix 사용

##참고 ** np.mat은 이 버전에서 쓰이진 않는다 여기서는 np.asmatrix 이렇게 쓰인다 

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
